# Generated by Django 4.2 on 2025-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookingformmodel_bookingtextmodel_roommodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.FileField(blank=True, null=True, upload_to='tda_counter_icons/')),
                ('icon1_text', models.CharField(max_length=255)),
                ('icon1_des', models.CharField(max_length=255)),
                ('icon2', models.FileField(blank=True, null=True, upload_to='tda_counter_icons/')),
                ('icon2_text', models.CharField(max_length=255)),
                ('icon2_des', models.CharField(max_length=255)),
                ('icon3', models.FileField(blank=True, null=True, upload_to='tda_counter_icons/')),
                ('icon3_text', models.CharField(max_length=255)),
                ('icon3_des', models.CharField(max_length=255)),
                ('icon4', models.FileField(blank=True, null=True, upload_to='tda_counter_icons/')),
                ('icon4_text', models.CharField(max_length=255)),
                ('icon4_des', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tda_counter_images/')),
                ('des', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
