# Generated by Django 4.2 on 2025-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_countermodel_homemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
