# Generated by Django 4.2 on 2025-06-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categeory',
            new_name='category',
        ),
    ]
