# Generated by Django 4.2 on 2025-06-24 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_countermodel_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('position', ckeditor.fields.RichTextField()),
                ('model_image', models.ImageField(blank=True, null=True, upload_to='tda/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingformmodel',
            name='customer_zipcode',
            field=models.PositiveIntegerField(),
        ),
    ]
