# Generated by Django 4.2 on 2025-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_countermodel_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodel',
            name='model_image',
            field=models.ImageField(blank=True, default='', upload_to='tda/'),
        ),
    ]
