# Generated by Django 4.2 on 2025-06-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_categeory_post_category'),
        ('myapp', '0007_alter_testimonialmodel_model_image'),
    ]

    operations = [
    ]
